//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientSetting
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public Nullable<decimal> PercentageDeduction { get; set; }
        public Nullable<int> DefaultRevenueItemId { get; set; }
        public Nullable<bool> ShowAmountUnpaid { get; set; }
        public Nullable<int> WithholdingTaxRevenueItem { get; set; }
        public Nullable<int> ConsumptionTaxRevenueId { get; set; }
        public Nullable<int> PayeeRevenueItem { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
