//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EOD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EOD()
        {
            this.EODPaymentNotificationLogs = new HashSet<EODPaymentNotificationLog>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int TerminalId { get; set; }
        public decimal Amount { get; set; }
        public bool Status { get; set; }
        public byte[] timestamp { get; set; }
        public int Count { get; set; }
        public string TransactionReference { get; set; }
    
        public virtual Terminal Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EODPaymentNotificationLog> EODPaymentNotificationLogs { get; set; }
    }
}
