//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EODPaymentNotificationLog
    {
        public int Id { get; set; }
        public int EODId { get; set; }
        public string SessionId { get; set; }
        public string SourceBankCode { get; set; }
        public int ChannelCode { get; set; }
        public string CustomerName { get; set; }
        public int BillerId { get; set; }
        public string BillerName { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Fee { get; set; }
        public string TransactionFeeBearer { get; set; }
        public string SplitType { get; set; }
        public string DestinationBankCode { get; set; }
        public string Narration { get; set; }
        public string PaymentReference { get; set; }
        public System.DateTime TransactionInitiatedDate { get; set; }
        public System.DateTime TransactionApprovalDate { get; set; }
    
        public virtual EOD EOD { get; set; }
    }
}
