//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentId { get; set; }
        public decimal Amount { get; set; }
        public string Email { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Reference { get; set; }
        public string Target { get; set; }
        public bool Status { get; set; }
        public string Method { get; set; }
        public Nullable<int> WalletId { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual TransactionLog TransactionLog { get; set; }
        public virtual User User { get; set; }
        public virtual Wallet Wallet { get; set; }
    }
}
