//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamsICSLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalUpdateLog
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int TerminalId { get; set; }
        public string Field { get; set; }
        public string OldValues { get; set; }
        public string NewValues { get; set; }
        public string Detail { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
